services:
  gateway:
    build:
      context: .
      dockerfile: cmd/gateway/Dockerfile
    environment:
      - GATEWAY_PORT=8080

  client_1:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    environment:
      - INSTANCE_ID=1
      - INSTANCE_TOTAL=1
      - GATEWAY_HOST=gateway
      - GATEWAY_PORT=8080
      - INPUT_DIR=/data/client_1
      - BATCH_SIZE=100
    volumes:
      - ../input:/data
    depends_on:
      - gateway

  filter_1:
    build:
      context: .
      dockerfile: cmd/filter/Dockerfile
    environment:
      - INSTANCE_ID=1
      - INSTANCE_TOTAL=1

  joiner_1:
    build:
      context: .
      dockerfile: cmd/joiner/Dockerfile
    environment:
      - INSTANCE_ID=1
      - INSTANCE_TOTAL=3

  joiner_2:
    build:
      context: .
      dockerfile: cmd/joiner/Dockerfile
    environment:
      - INSTANCE_ID=2
      - INSTANCE_TOTAL=3

  joiner_3:
    build:
      context: .
      dockerfile: cmd/joiner/Dockerfile
    environment:
      - INSTANCE_ID=3
      - INSTANCE_TOTAL=3

  counter_1:
    build:
      context: .
      dockerfile: cmd/counter/Dockerfile
    environment:
      - INSTANCE_ID=1
      - INSTANCE_TOTAL=2

  counter_2:
    build:
      context: .
      dockerfile: cmd/counter/Dockerfile
    environment:
      - INSTANCE_ID=2
      - INSTANCE_TOTAL=2

